services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 194393
      MYSQL_DATABASE: restaurant-chain
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: 194393
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
